### PR TITLE
Fixed issue with gsheets export.

### PR DESCRIPTION
**Pull request by leonholub**
## Purpose
Export to Google sheets is currently failing because of a missing url configuration. Fixed the config for the url path ` /oauth2callback/export_to_gsheet`

I assume this fixes _Related ticket: #438 _

### CODE REVIEW

**Comment by leonholub** [comment]
@jefmoura ok, added a view test for export_to_gsheet.

**Comment by leonholub** [comment]
Added some changes but the checks are failing. Will fix it now

**Comment by jefmoura** [comment]
Resolve the conflicts @leonholub

**Comment by jefmoura** [comment]
Resolve the conflicts @leonholub

**Pull request merged**
