### PR TITLE
Bugfixes and Feature additions in latest MC release

### PR DESCRIPTION
**Pull request by sanjuroj**

### CODE REVIEW

**Comment by Menda** [comment]
Some points:

* There is no description or reference to ticket.
* Merge conflicts should not appear in the pull request. Fix them locally and rebase your branch.
* There are conflicting files.

**Comment by sanjuroj** [comment]
Thanks for the feedback!  I'll work on resolving the merge conflicts.  

Many of the commits do have issue references but some don't.  Rather than rebasing all of those commits, can they be accepted as is if we commit to ensuring that future pull requests have tickets associated with each commit?

**Comment by glind** [comment]
@sanjuroj Yes if you can fix the conflicts we will review the commit as a whole.  Also, would be better to submit one or 2 issues per pull request so we can review easier.  Thanks

**Comment by sanjuroj** [comment]
@glind Agreed, there was way too much in this one.  I'm hoping to have an updated pull request tomorrow for you to start evaluating.

**Comment by Menda** [comment]
Hey @sanjuroj , it's pretty difficult to keep all those changes up to date and not to have conflicts. In my opinion it would be nicer if you did one pull request per ticket that you are addressing. You have already that pretty much done in the commits, where you reference to the tickets. It would also be much easier for us to review and to get done job fast.

**Comment by sanjuroj** [comment]
I've gotten sidetracked.  I'll close this and reopen/open a new one when I can get back to it.  Sorry for letting it hang out here for so long.

**Comment by sanjuroj** [comment]
@Menda Ok, had to fix some urgent issues on our end.  I can start working on this pull request again, when you have time.

**Comment by Menda** [comment]
@sanjuroj More than reopening this Pull Request, I would be better take each individual ticket that needs to be fixed and create a new pull request for each one.

**Pull request closed without merging**
